<NavBar>:
    md_bg_color: 1, 1, 1, 1
    selected_color: app.theme_cls.primary_color
    text_color: 0.5, 0.5, 0.5, 1
    active_color_light: app.theme_cls.primary_color
    active_color_dark: app.theme_cls.primary_color
    elevation: 12
    height: dp(70)  # un peu plus haut pour mobile

    MDBottomNavigationItem:
        # Les items sont créés dynamiquement en Python
        # Mais tu peux en ajouter statiquement ici si tu préfères
        pass
